### ISSUE TITLE
Management Auth SDK

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-sdk-js#12]
Create control plane auth SDK based of keycloak-js

**Comment by wtrocki** [comment]
Done investigation if we should include auth SDK right now. 
It seems like we are missing a generic keycloak client for management SDK's (CLI, UI use different ones, not sure which to use). Flagging this as area we need to learn more to build SDK - possibly sync with Security leads (@pmuir)

**Comment by pmuir** [comment]
It would be good to pull a slightly simpler setup for the keycloak js into the SDK, and also the refresh token caching that I wrote.

**Comment by wtrocki** [comment]
Problem is that there is no keycloak client that we can use in generic way. 
Like current scenario is that if you want to get sso.redhat.com integration you need to ping some person from sso.redhat.com team. Data planes are even more problems right now. We are currently solving so many internal problems with SDK's, but my feeling is that we are still not ready for usage outside - once there is separate security service with proper openapi we can put some authorization and authentication SDK in place. My feeling is that doing it now will be widely premature. (can discuss)

**Comment by wtrocki** [comment]
Documentation created for the moment https://redhat-developer.github.io/app-services-sdk-js/docs/authentication.html
