### ISSUE TITLE
Move mas-mock to js-sdk

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-sdk-js#13]
Controversial but we need to have mocking capability and JS-SDK seems to be the best place to do it.

**Comment by wtrocki** [comment]
CC @craicoverflow

**Comment by wtrocki** [comment]
I forgot to ask about this. Pinging again

**Comment by craicoverflow** [comment]
Didn't realise this was a question. Yeah, this would be fine as I don't know where else it should go tbh. We would ideally containerise and publish the mocks to Quay or something?

**Comment by wtrocki** [comment]
Yes.. That will be good as well so each SDK can pull it out as container rather than anything else.

CC @pmuir @ajaypratap003 Any comments before we start doing this?

**Comment by wtrocki** [comment]
Done. @ajaypratap003 you can play with this on kas-ui
