### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-sdk-js#3]
Before moving to the automation phase we should set up an initial project architecture following best practices.

## Proposed layout

 layout:

```shell
├── packages
│   ├── rhoas-sdk ## Aggregate containing entire SDK as whole
│   ├── kafka-management-sdk
│   ├── registry-management-sdk
    ├── common-sdk (contains auth, config, logging etc.)
scripts
.openapi ## source for apis used for tagging - we need that as apis are in different formats etc. (we should not delete apis etc.
```

**Comment by wtrocki** [comment]
CC @craicoverflow

**Comment by wtrocki** [comment]
I did not use `mgmt` as shortcut looks unprofessional to me :D Using whole `manangement`

**Comment by craicoverflow** [comment]
It's a Go design philosophy:

> Abbreviate judiciously. Package names may be abbreviated when the abbreviation is familiar to the > programmer. Widely-used packages often have compressed names:

> * strconv (string conversion)
> * syscall (system call)
> * fmt (formatted I/O)

Source: https://blog.golang.org/package-names

**Comment by craicoverflow** [comment]
> For dataplane we can use functional names - kafka-instance-admin etc.

You said last week we should not use "admin" as it is not future proofed as the API could include non-admin activities like producting messages. `instance-api` is what I was thinking to use.

**Comment by wtrocki** [comment]
> You said last week we should not use "admin" 

Done my reasearch till then.
Kafka dataplane will be always used for UI/CLI. 
HTTP bridge will be deploying strimzi bridge which doesnt have admin commands. 

Why we talk about go in JS repo?

**Comment by wtrocki** [comment]
I have put thoughts into this and experimented with API and for JS-sdk creating anything else than actual OpenAPI SDK's for now will be overkill.

If there would be need for common-sdk at any point we can use them in the individual SDK's.
If we will get any requirement for the functionalities to be part of the SDK we can always add that later.

NOTE: 
JS-SDK is using different flow than golang SDK. We are not generating SDK when file is updated - Just PR with new openapi file is created. This is due to the fact that generation for JS looks differently and we have extra elements like Examples documentation that needs to be verified and adjusted anyway. It is better to have follow up PR with generation that has everything included.
