### ISSUE TITLE
Update mock for the kafka-admin API

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-sdk-js#65]
Base on the https://github.com/redhat-developer/app-services-sdk-go/pull/132/files

**Comment by craicoverflow** [comment]
Need to confirm whether all of those changes are in production before doing this.

**Comment by wtrocki** [comment]
yes, but mock is kinda grey area. I got pinged by frontend wanting to adjust no new api on mock and then wait for release - value of mock
