### ISSUE TITLE
Investigate if we need lerna for releases

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-sdk-js#8]
Lerna seems to be made redundant by npm7 and yarn.
Investigate how we can release without lerna

**Comment by wtrocki** [comment]
Actually lerna seems outdated and since our approach will have individual packages we can simply use any workspaces solution.


I'm investigating using:
- Homebrewn release on top of yarn/npm workspace
- https://github.com/semantic-release/semantic-release
- https://github.com/atlassian/changesets
- https://github.com/pnpm/pnpm

Some of those provide changelog that conflict with current changelog system using in go and go sdk.

**Comment by wtrocki** [comment]
FYI @craicoverflow if you have experience with any of those

**Comment by wtrocki** [comment]
After investigation, I'm wondering if we really need individual package releases. 
Problem I see is how we actually generate changelog for those (extension we currently use in go doesn't seem to support filtering) and how we track/major/minor changes.

If we do it looks like there is no tool that will support our use case and we will need to write our own process/tool based of yarn workspaces. 

There are two use cases:

- We want to release specific SDK (that was changed)
- We want to release all SDK's 

Spike results for changesets:
https://github.com/redhat-developer/app-services-sdk-js/pull/16

**Comment by craicoverflow** [comment]
> After investigation, I'm wondering if we really need individual package releases.

Maybe we do not need individual package releases. It will make things more complex in multiple ways. There are huge benefits of having individual releases, but the benefits do not seem to outweigh the complexities.

**Comment by wtrocki** [comment]
That is great point. Maybe we can simply do release whole package like we used to do with graphback?
Since this was area you were exploring I will follow your advice

I could not find any tool that does releases this way so build our own that works: https://github.com/redhat-developer/app-services-sdk-js/pull/18

This still requires a manual version bumps before release etc.

**Comment by wtrocki** [comment]
We are not going to use any tool for releases
