### ISSUE TITLE
Delete registry mock API is not working

### ISSUE THREAD

**Issue by ajaypratap003** [redhat-developer/app-services-sdk-js#97]
Delete registry mock API is not working

Error:
code: "registries-MGMT-103"
href: "/api/serviceregistry_mgmt/v1/errors/103"
id: "103"
kind: "Error"
operation_id: "1iWIimqGcrDuL61aUxIZqBTqNRa"
reason: "Missing or invalid id field"

**Comment by wtrocki** [comment]
I cannot replicate this. 
Procedure:

1. Checkout repository
2. cd packages/api-mock
3. yarn start
4. yarn api:registry-management

Passing ID and getting proper error code
![Screenshot 2021-06-29 at 11 32 45](https://user-images.githubusercontent.com/981838/123782942-bf0b0d80-d8cd-11eb-8f14-cf05c702c4c6.png)

**Comment by wtrocki** [comment]
What might be happening is that your code has some hooks issues that executes action twice and second response will be this error. This error is basically information that registry with that ID doesn't exist. 

For future issues please provide more info:

- Show list of the registries that have this specific ID present
- Show delete call that fails for the same ID

**Comment by wtrocki** [comment]
Closing, but feel free to reopen when more info is provided.
