### ISSUE TITLE
Seems registry models are not exported in sdk

### ISSUE THREAD

**Issue by ajaypratap003** [redhat-developer/app-services-sdk-js#98]
Module '"../../../../../node_modules/@rhoas/registry-management-sdk/dist"' has no exported member 'RegistryListRest'.

**Comment by wtrocki** [comment]
This is most likely misconfiguration on your project - Can you show me your ts-config?
Node_modules should be never compiled itself. Dist have compiled source and definition files.

**Comment by wtrocki** [comment]
# Verification

1. git clone 
2. cd examples 
3. Change serviceRegistry to use production/published package
4. Run service registry example

Code compiles and runs correctly.

**Comment by wtrocki** [comment]
Another issue would be invalid common JS import. 
All imports for SDK needs to use package name: "@rhoas/registry-management-sdk"
Using filesystem imports might cause such issues. 
I'm closing this but you should ping me on PR/Code that causes this issue so we can resolve that on your end.
